/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- route handlers intentionally expose NextResponse | undefined through mocked auth unions.
import { beforeEach,describe,expect,it,vi } from "vitest";
import { NextResponse } from "next/server";
const auth=vi.fn(),list=vi.fn(),read=vi.fn(),all=vi.fn(),archive=vi.fn(),count=vi.fn(),broadcast=vi.fn();
vi.mock("@/lib/api/requireApiUser",()=>({requireApiUser:()=>auth()}));
vi.mock("@/lib/server/friends/studyTogether",()=>({listNotifications:(...a:unknown[])=>list(...a),markNotificationRead:(...a:unknown[])=>read(...a),markAllNotificationsRead:(...a:unknown[])=>all(...a),archiveChallengeNotification:(...a:unknown[])=>archive(...a),getUnreadNotificationCount:(...a:unknown[])=>count(...a),mapStudyTogetherRouteError:()=>null}));
vi.mock("@/lib/server/friends/realtimeBroadcast",()=>({broadcastSocialEvent:(...a:unknown[])=>broadcast(...a)}));
import {GET,PATCH,POST} from "./route";import {GET as unread} from "./unread-count/route";import {POST as react} from "../reactions/route";
const ID="11111111-1111-4111-8111-111111111111",OTHER="22222222-2222-4222-8222-222222222222";const req=(url:string,method="GET",body?:unknown)=>new Request(url,{method,headers:{"content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});
beforeEach(()=>{vi.clearAllMocks();auth.mockResolvedValue({supabase:{rpc:vi.fn().mockResolvedValue({data:{recipientUserId:OTHER,reactionId:"xin_chao"},error:null})},user:{id:ID}});});
describe("notifications",()=>{it("authenticates before validation",async()=>{auth.mockResolvedValue({error:NextResponse.json({error:"unauthorized"},{status:401})});expect((await PATCH(req("http://x","PATCH",{}))).status).toBe(401);expect(read).not.toHaveBeenCalled();});it("bounds list and does not mark read",async()=>{list.mockResolvedValue({notifications:[]});expect((await GET(req("http://x?limit=20"))).status).toBe(200);expect(read).not.toHaveBeenCalled();expect((await GET(req("http://x?limit=51"))).status).toBe(400);});it("supports targeted read, read all, archive, and count",async()=>{read.mockResolvedValue({ok:true});all.mockResolvedValue({count:2});archive.mockResolvedValue({ok:true});count.mockResolvedValue(3);expect((await PATCH(req("http://x","PATCH",{notificationId:ID}))).status).toBe(200);expect((await POST(req("http://x","POST",{action:"mark_all_read"}))).status).toBe(200);expect((await POST(req("http://x","POST",{action:"archive_invite",sessionId:OTHER}))).status).toBe(200);expect(await (await unread()).json()).toEqual({data:{count:3}});});it("returns durable reaction success when broadcast fails",async()=>{broadcast.mockResolvedValue(false);expect((await react(req("http://x","POST",{recipientUserId:OTHER,reactionId:"xin_chao"}))).status).toBe(200);});});
