import { NextResponse } from "next/server";
import { z } from "zod";
import { requireApiUser } from "@/lib/api/requireApiUser";
import { createStudyChallenge, listStudyChallenges, mapStudyTogetherRouteError } from "@/lib/server/friends/studyTogether";
const createSchema=z.object({recipientId:z.string().uuid(),outputId:z.string().uuid(),mode:z.enum(["practice","score"]).default("score"),deadlineAt:z.string().datetime().nullable().default(null),message:z.string().trim().max(500).nullable().default(null),revealPolicy:z.enum(["immediate","after_both_complete","after_deadline"]).default("after_both_complete")}).superRefine((v,c)=>{if(v.deadlineAt){const t=Date.parse(v.deadlineAt);if(t<=Date.now()||t>Date.now()+365*86400000)c.addIssue({code:"custom",message:"deadline"});}});
const fail=(e:unknown)=>{const m=mapStudyTogetherRouteError(e);return NextResponse.json(m?.body??{error:"social_unavailable"},{status:m?.status??500});};
export async function GET(request:Request){const auth=await requireApiUser();if("error" in auth)return auth.error;const q=new URL(request.url).searchParams;const parsed=z.object({limit:z.coerce.number().int().min(1).max(50).default(20),before:z.string().datetime().nullable().default(null)}).safeParse({limit:q.get("limit")??undefined,before:q.get("before")});if(!parsed.success)return NextResponse.json({error:"invalid"},{status:400});try{return NextResponse.json({data:await listStudyChallenges(auth.supabase,parsed.data.limit,parsed.data.before)});}catch(e){return fail(e);}}
export async function POST(request:Request){const auth=await requireApiUser();if("error" in auth)return auth.error;let body;try{body=createSchema.parse(await request.json());}catch{return NextResponse.json({error:"invalid"},{status:400});}try{return NextResponse.json({data:await createStudyChallenge(auth.supabase,body)});}catch(e){return fail(e);}}
export const runtime="nodejs";
