"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useLocale } from "@/components/locale/LocaleProvider";
import { createStudyChallenge, startOrResumeCreatorAttempt, type EligibleChallengeQuiz, type StudyMode } from "@/lib/client/studyTogether";

export function StudyChallengeDialog({ open, onOpenChange, recipientId, quizzes }: { open: boolean; onOpenChange: (open: boolean) => void; recipientId: string; quizzes: readonly EligibleChallengeQuiz[] }) {
  const { messages } = useLocale(); const copy = messages.studyTogether; const router = useRouter();
  const eligible = quizzes.filter((quiz) => quiz.status === "ready" && quiz.questionCount > 0);
  const [outputId, setOutputId] = useState(eligible[0]?.outputId ?? ""); const [mode, setMode] = useState<StudyMode>("score"); const [deadline, setDeadline] = useState("none"); const [message, setMessage] = useState(""); const [sessionId, setSessionId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const send = async () => { setBusy(true); setError(""); try { const days = deadline === "1" ? 1 : deadline === "3" ? 3 : deadline === "7" ? 7 : 0; const result = await createStudyChallenge({ recipientId, outputId, mode, deadlineAt: days ? new Date(Date.now() + days * 86400000).toISOString() : null, message: message.trim() || null, revealPolicy: "after_both_complete" }); setSessionId(result.sessionId); } catch { setError(copy.unavailable); } finally { setBusy(false); } };
  const start = async () => { setBusy(true); try { const attempt = await startOrResumeCreatorAttempt(sessionId); router.push(attempt.playHref); } catch { setError(copy.unavailable); } finally { setBusy(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{copy.title}</DialogTitle><DialogDescription>{copy.description}</DialogDescription></DialogHeader>{sessionId ? <div className="space-y-4"><p>{copy.sent}</p><Button disabled={busy} onClick={() => void start()}>{copy.start}</Button></div> : <div className="grid gap-4"><label>{copy.chooseQuiz}<select className="mt-1 w-full rounded-lg border bg-background p-2" value={outputId} onChange={(event) => setOutputId(event.target.value)}>{eligible.map((quiz) => <option key={quiz.outputId} value={quiz.outputId}>{quiz.title} ({quiz.questionCount})</option>)}</select></label><label>{copy.mode}<select className="mt-1 w-full rounded-lg border bg-background p-2" value={mode} onChange={(event) => setMode(event.target.value as StudyMode)}><option value="score">{copy.scoreMode}</option><option value="practice">{copy.practiceMode}</option></select></label><label>{copy.deadline}<select className="mt-1 w-full rounded-lg border bg-background p-2" value={deadline} onChange={(event) => setDeadline(event.target.value)}><option value="none">{copy.noDeadline}</option><option value="1">{copy.oneDay}</option><option value="3">{copy.threeDays}</option><option value="7">{copy.sevenDays}</option></select></label><label>{copy.optionalMessage}<textarea className="mt-1 w-full rounded-lg border bg-background p-2" maxLength={500} value={message} onChange={(event) => setMessage(event.target.value)} /></label></div>}{error ? <p role="alert" className="text-destructive">{error}</p> : null}{!sessionId ? <DialogFooter><Button disabled={busy || !outputId} onClick={() => void send()}>{copy.send}</Button></DialogFooter> : null}</DialogContent></Dialog>;
}
