begin;
create index if not exists friend_requests_social_page_idx on public.friend_requests(status,created_at desc,id desc);
create index if not exists user_blocks_owner_page_idx on public.user_blocks(blocker_id,created_at desc,blocked_id desc);
create index if not exists study_together_recipient_page_idx on public.study_together_sessions(recipient_id,status,created_at desc,id desc);
create index if not exists direct_conversations_user_low_page_idx on public.direct_conversations(user_low_id,last_message_at desc,id desc);
create index if not exists direct_conversations_user_high_page_idx on public.direct_conversations(user_high_id,last_message_at desc,id desc);

create or replace function public.list_social_friends(p_limit integer,p_cursor jsonb default null) returns jsonb language sql security definer set search_path=public as $$
with owned as (select case when fr.sender_id=auth.uid() then fr.recipient_id else fr.sender_id end user_id from public.friend_requests fr where auth.uid() is not null and fr.status='accepted' and auth.uid() in(fr.sender_id,fr.recipient_id)), rows as (select o.user_id,p.username,case when a.last_active_at>=now()-interval '5 minutes' then 0 when a.last_active_at is not null then 1 else 2 end presence_rank,a.last_active_at from owned o join public.profiles p on p.id=o.user_id left join private.social_activity a on a.user_id=o.user_id where not private.social_users_blocked(auth.uid(),o.user_id)), page as (select * from rows where p_cursor is null or (presence_rank,coalesce(username,''),user_id::text)>((p_cursor->>0)::int,p_cursor->>1,p_cursor->>2) order by presence_rank,coalesce(username,''),user_id limit least(greatest(p_limit,1),51)) select jsonb_build_object('items',coalesce(jsonb_agg(jsonb_build_object('userId',user_id,'username',username,'presenceRank',presence_rank,'presence',case presence_rank when 0 then 'online' when 1 then 'recently_active' else 'offline' end,'lastActiveAt',last_active_at) order by presence_rank,coalesce(username,''),user_id),'[]'),'totalCount',(select count(*) from rows)) from page $$;
create or replace function public.list_social_friend_requests(p_limit integer,p_cursor jsonb default null,p_direction text default 'incoming') returns jsonb language sql security definer set search_path=public as $$ with rows as (select fr.id request_id,case when p_direction='incoming' then fr.sender_id else fr.recipient_id end other_user_id,p.username,fr.created_at from public.friend_requests fr join public.profiles p on p.id=case when p_direction='incoming' then fr.sender_id else fr.recipient_id end where auth.uid() is not null and p_direction in('incoming','outgoing') and fr.status='pending' and ((p_direction='incoming' and fr.recipient_id=auth.uid()) or (p_direction='outgoing' and fr.sender_id=auth.uid()))),page as(select * from rows where p_cursor is null or (created_at,request_id)<((p_cursor->>0)::timestamptz,(p_cursor->>1)::uuid) order by created_at desc,request_id desc limit least(greatest(p_limit,1),51)) select jsonb_build_object('items',coalesce(jsonb_agg(jsonb_build_object('requestId',request_id,'otherUserId',other_user_id,'username',username,'createdAt',created_at) order by created_at desc,request_id desc),'[]'),'totalCount',(select count(*) from rows)) from page $$;
create or replace function public.list_social_invites(p_limit integer,p_cursor jsonb default null) returns jsonb language sql security definer set search_path=public as $$ with rows as(select s.id session_id,s.creator_id,p.username,s.snapshot->>'title' title,s.created_at from public.study_together_sessions s join public.profiles p on p.id=s.creator_id where auth.uid() is not null and s.recipient_id=auth.uid() and s.status='pending'),page as(select * from rows where p_cursor is null or (created_at,session_id)<((p_cursor->>0)::timestamptz,(p_cursor->>1)::uuid) order by created_at desc,session_id desc limit least(greatest(p_limit,1),51)) select jsonb_build_object('items',coalesce(jsonb_agg(jsonb_build_object('sessionId',session_id,'creatorId',creator_id,'username',username,'title',title,'createdAt',created_at) order by created_at desc,session_id desc),'[]'),'totalCount',(select count(*) from rows)) from page $$;
create or replace function public.list_social_conversations(p_limit integer,p_cursor jsonb default null) returns jsonb language sql security definer set search_path=public as $$ with rows as(select c.id conversation_id,c.last_message_at,case when c.user_low_id=auth.uid() then c.user_high_id else c.user_low_id end peer_id from public.direct_conversations c where auth.uid() is not null and auth.uid() in(c.user_low_id,c.user_high_id)),page as(select r.*,p.username,(select body from public.direct_messages m where m.conversation_id=r.conversation_id order by created_at desc,id desc limit 1) preview from rows r join public.profiles p on p.id=r.peer_id where p_cursor is null or (coalesce(r.last_message_at,'epoch'),r.conversation_id)<(coalesce((p_cursor->>0)::timestamptz,'epoch'),(p_cursor->>1)::uuid) order by r.last_message_at desc nulls last,r.conversation_id desc limit least(greatest(p_limit,1),51)) select jsonb_build_object('items',coalesce(jsonb_agg(jsonb_build_object('conversationId',conversation_id,'peerId',peer_id,'username',username,'lastMessageAt',last_message_at,'preview',preview) order by last_message_at desc nulls last,conversation_id desc),'[]')) from page $$;
create or replace function public.list_social_blocks(p_limit integer,p_cursor jsonb default null) returns jsonb language sql security definer set search_path=public as $$ with rows as(select b.blocked_id user_id,p.username,b.created_at blocked_at from public.user_blocks b join public.profiles p on p.id=b.blocked_id where auth.uid() is not null and b.blocker_id=auth.uid()),page as(select * from rows where p_cursor is null or (blocked_at,user_id)<((p_cursor->>0)::timestamptz,(p_cursor->>1)::uuid) order by blocked_at desc,user_id desc limit least(greatest(p_limit,1),51)) select jsonb_build_object('items',coalesce(jsonb_agg(jsonb_build_object('userId',user_id,'username',username,'blockedAt',blocked_at) order by blocked_at desc,user_id desc),'[]'),'totalCount',(select count(*) from rows)) from page $$;
revoke all on function public.list_social_friends(integer,jsonb),public.list_social_friend_requests(integer,jsonb,text),public.list_social_invites(integer,jsonb),public.list_social_conversations(integer,jsonb),public.list_social_blocks(integer,jsonb) from public,anon;
grant execute on function public.list_social_friends(integer,jsonb),public.list_social_friend_requests(integer,jsonb,text),public.list_social_invites(integer,jsonb),public.list_social_conversations(integer,jsonb),public.list_social_blocks(integer,jsonb) to authenticated;
commit;
